
// export const metadata = {
//   title: "Contact page",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning>Contact page me aapka swagath hai.{children}</body>
//     </html>
//   );
//}